name = "QuantumDAGs"
uuid = "c5e1564c-46d0-4d88-984f-9aacba45ce63"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com> and contributors"]
version = "0.0.1"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MEnums = "7c338ca5-b20e-417b-9799-aae6c720705e"

[compat]
MEnums = "0.1"
Graphs = "1.8"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
